ProyekAkhir_Teknet/Models/Akun.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyekAkhir_Teknet.Models
{
    public class Akun
    {

        public string username { get; set; }
        public string password { get; set; }

    }
}

ProyekAkhir_Teknet/Models/Pasien.cs
namespace ProyekAkhir_Teknet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasien
    {
        public int Pasien_ID { get; set; }
        public string Nama_Pasien { get; set; }
        public string No_Hp { get; set; }
        public string Gejala_Pasien { get; set; }
        public string Alamat { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
    }
}

ProyekAkhir_Teknet/Models/Register.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyekAkhir_Teknet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vaksin_TeknetEntities : DbContext
    {
        public Vaksin_TeknetEntities()
            : base("name=Vaksin_TeknetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pasien> Pasiens { get; set; }
    }
}

ProyekAkhir_Teknet/Models/Register.Designer.cs
// T4 code generation is enabled for model 'D:\Perkuliahan\Semester_4\.NET\Proyek\Baru\ProyekAkhir_Teknet\ProyekAkhir_Teknet\Models\Register.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

ProyekAkhir_Teknet/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace ProyekAkhir_Teknet.Models
{

public class Register
{

    public int Pasien_ID { get; set; }

    [Required]
    [Display(Name = "Nama Lengkap")]
    public string Nama_Pasien { get; set; }

    [Required]
    [Display(Name = "No Hp")]
    public string No_Hp { get; set; }


    [Required]
    [Display(Name = "Gejala Pasien")]
    public string Gejala_Pasien { get; set; }
 
    
    [Required]
    [Display(Name = "Alamat")]
    public string Alamat { get; set; }


        
    [Required]
    [Display(Name = "Username")]
    public string Username { get; set; }


    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }
}
}

ProyekAkhir_Teknet/Controllers/AkunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyekAkhir_Teknet.Models;
using System.Data.SqlClient;

namespace ProyekAkhir_Teknet.Controllers
{
    public class AkunController : Controller
    {

        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        // GET: Akun
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        void ConnectionString()
        {
            con.ConnectionString = "data source=LAPTOP-OEHKD8AQ; database=Vaksin_Teknet; integrated security = SSPI;";
        }
        [HttpPost]
        public ActionResult Verify(Pasien pasien)
        {

            ConnectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "SELECT * FROM Pasien WHERE username='" + pasien.Username + "' AND password ='" + pasien.Password + "'";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                con.Close();

                return View("Berhasil");
            }
            else
            {
                con.Close();

                return View("Error");
            }
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterPasien(Register registerDetails)
        {
            if (ModelState.IsValid)
            {
                using (var databaseContext = new Vaksin_TeknetEntities())
                {



                    Pasien reglog = new Pasien();

                    reglog.Pasien_ID = registerDetails.Pasien_ID;
                    reglog.Nama_Pasien = registerDetails.Nama_Pasien;
                    reglog.No_Hp = registerDetails.No_Hp;
                    reglog.Alamat = registerDetails.Alamat;
                    reglog.Username = registerDetails.Username;
                    reglog.Gejala_Pasien = registerDetails.Gejala_Pasien;
                    reglog.Password = registerDetails.Password;

                    databaseContext.Pasiens.Add(reglog);
                
                    databaseContext.SaveChanges();

                }

                ViewBag.Message = "User Details Saved";
                return View("Register");
            }
            else
            {

                return View("Register", registerDetails);
            }
        }
    }
}

ProyekAkhir_Teknet/Views/Akun/Berhasil.cshtml
@{
    ViewBag.Title = "Berhasil";
    Layout = "~/Views/LoginLayout.cshtml";
}

<h2>Berhasil</h2>

ProyekAkhir_Teknet/Views/Akun/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/LoginLayout.cshtml";
}

<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Login</title>
    <!-- Custom Theme files -->
    <link href="style/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <!--Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!--Google Fonts-->
</head>
<body>
    <!--header start here-->
    <form action="Verify" method="post">


    <div class="login">
        <div class="login-main">
            <div class="login-top">
                <img src="image/head-img.png" alt="" />
                <h1>Login <span class="anc-color"> to your account</span> </h1>
                <h2>Login with</h2>
                <ul>
                    <li><a class="fa" href="#"> </a></li>
                    <li><a class="tw" href="#"> </a></li>
                    <li><a class="g" href="#"> </a></li>
                </ul>
                <h3> or</h3>
                <input type="text" placeholder="Username" name="username" required="">
                <input type="password" placeholder="Password" name= "password" required="">
                <div class="login-bottom">
                    <div class="login-check">
                        <label class="checkbox"><input type="checkbox" name="checkbox" checked><i> </i> Remember Me</label>
                    </div>
                    <div class="login-para">
                        <p><a href="#"> Forgot Password </a></p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <input type="submit" value="Login" />
                <h4> Don't Have an account ?  @Html.ActionLink("Register Now", "Register")"</a></h4>
            </div>
        </div>
    </div>
    <div class="copyright">
        <p>Template by <a href="http://w3layouts.com/"> W3layouts </a></p>
    </div>
    <!--header end here-->
    </form>
</body>
</html>

ProyekAkhir_Teknet/Views/Akun/Register.cshtml
@model ProyekAkhir_Teknet.Models.Register

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/LoginLayout.cshtml";
}

<h2>Register</h2>

@using (Html.BeginForm("RegisterPasien","Akun")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Register</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    
    <div class="form-group">
        @Html.LabelFor(model => model.Nama_Pasien, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nama_Pasien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nama_Pasien, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.No_Hp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.No_Hp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.No_Hp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gejala_Pasien, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gejala_Pasien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gejala_Pasien, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Login")
</div>

ProyekAkhir_Teknet/Views/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/style/style.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>